//import $ from 'jquery';
var $ = 'jquery';
console.log("this is working");

//Getting text from div class using a click method when the document is ready
//As C# does whitespace removal with .trim() method does the same
$(document).ready(function(){
    var h2Text = $(".mainHeader").text();
    $("h2").click(function(){
        console.log(h2Text);
    });

    //Getting text from div class
    var sectionDivCol2 = $(".col2").text().trim();
    console.log(sectionDivCol2);

    //Getting text from a  div id
    var sectionDivCol1 = $("#col1").text().trim();
    console.log(sectionDivCol1);

    $(document).keyup(function(){
        $(".mainHeader").append(sectionDivCol1);
    });

    function createHTMLTags(tag, classInfo, text){
        classInfo = " class=\"" + classInfo + "\"";
        //var startTag = "<" + tag + classInfo + ">"
        var startTag = "<" + tag + ">";
        var endTag = "</" + tag + ">";
        var finalTag;
        finalTag = startTag + text + endTag;
        var stupidClasses = $(finalTag).addClass(classInfo);
        console.log(stupidClasses);
        $("body").append(stupidClasses);
        

    }

    omdbAPICall();
    //createHTMLTags("h2", "" , "This is an autogenerated one!")
    //createHTMLTags("p", "" , "Yes you made it!")
    createHTMLTags("div", "alert alert-success col8", "Javascript is useful, in its own ways, for some people!");

    function omdbAPICall(){
        var query = "http://www.omdbapi.com/?t=frozen&y=&plot=short&apikey=40e9cece";
        $.getJSON({
            url: query
        }).done(function(response){
            console.log(response);
            var ratings = response.Ratings;
            for (var i = 0; i < ratings.length; i++) {
                console.log (ratings[i].Source);
                console.log (ratings[i].Value);
            }
        })
    }
})
